### ISSUE TITLE
New logo for BookLibrary

### ISSUE THREAD

**Issue by reallinfo** [hufan-Akari/BookLibrary#3]
I wanted to contribute to BookLibrary. I designed a logo for it. If you like it, I'll send you files and pr.
is there anything you want ?

![bl](https://user-images.githubusercontent.com/36298335/38468806-9c2a4b8e-3b53-11e8-9ad6-4f4400695c43.jpg)

**Comment by magic-akari** [comment]
It's awesome. Please send me pull request. Thanks.

**Comment by reallinfo** [comment]
Thank you. I sent pr. Please check.

https://github.com/hufan-akari/BookLibrary/pull/4

**Comment by reallinfo** [comment]
Here are all the files.

https://drive.google.com/drive/folders/1mnTI_GYMDTiSGovzFM3C2BNnmMStQlXI

If you have a problem, you can contact me.
