### ISSUE TITLE
python 3.x project or python 2.x ?

### ISSUE THREAD

**Issue by marc-odp** [hufan-Akari/BookLibrary#48]
I don't seem to find the information. Is this a python 3.x project ?

**Comment by marc-odp** [comment]
In the README I see `virtualenv ./venv`.
However, in Python 3, it is like this :
`python3 -m venv venv`
So I suppose it is a python 2.x project. Can you confirm ?
Do you plan to convert it to python 3.x ?

**Comment by magic-akari** [comment]
When I write this project, I used python2.
In fact it is compatible with python3.
And it is recommend using python3 now.

I will update the README to clarify it.
